name: ollama-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - aiofiles=24.1.0
  - aiohttp=3.11.18
  - aiomonitor=1.0.0
  - attrs=25.3.0
  - backoff=2.2.1
  - beautifulsoup4=4.13.4
  - cachetools=5.5.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - coloredlogs=15.0.1
  - contourpy=1.3.2
  - cryptography=44.0.2
  - cycler=0.12.1
  - dataclasses-json=0.6.7
  - Deprecated=1.2.18
  - emoji=2.14.1
  - faiss-cpu=1.11.0
  - filelock=3.18.0
  - filetype=1.2.0
  - flatbuffers=25.2.10
  - fonttools=4.57.0
  - frozenlist=1.6.0
  - google-api-core=2.24.2
  - google-auth=2.39.0
  - grpcio=1.71.0
  - h11=0.16.0
  - html5lib=1.1
  - httpx=0.28.1
  - huggingface-hub=0.30.2
  - humanfriendly=10.0
  - idna=3.10
  - Jinja2=3.1.6
  - joblib=1.4.2
  - kiwisolver=1.4.8
  - langchain=0.3.24
  - langchain-community=0.3.23
  - langchain-core=0.3.56
  - langchain-ollama=0.3.2
  - langchain-text-splitters=0.3.8
  - langchainhub=0.1.21
  - langdetect=1.0.9
  - langsmith=0.3.38
  - lxml=5.4.0
  - MarkupSafe=3.0.2
  - marshmallow=3.26.1
  - matplotlib=3.10.1
  - mpmath=1.3.0
  - multidict=6.4.3
  - networkx=3.4.2
  - nltk=3.9.1
  - numpy=2.2.5
  - olefile=0.47
  - ollama=0.4.8
  - onnx=1.17.0
  - onnxruntime=1.21.1
  - opencv-python=4.11.0.86
  - orjson=3.10.18
  - pandas=2.2.3
  - pillow=11.2.1
  - protobuf=5.29.4
  - psutil=7.0.0
  - pydantic=2.11.4
  - pyparsing=3.2.3
  - pypdf=5.4.0
  - python-dotenv=1.1.0
  - pytz=2025.2
  - PyYAML=6.0.2
  - RapidFuzz=3.13.0
  - regex=2024.11.6
  - requests=2.32.3
  - rsa=4.9.1
  - safetensors=0.5.3
  - scipy=1.15.2
  - six=1.17.0
  - soupsieve=2.7
  - SQLAlchemy=2.0.40
  - sympy=1.14.0
  - tenacity=9.1.2
  - timm=1.0.15
  - tokenizers=0.21.1
  - torch=2.7.0
  - torchvision=0.22.0
  - tqdm=4.67.1
  - transformers=4.51.3
  - typing-inspect=0.9.0
  - typing_extensions=4.13.2
  - tzdata=2025.2
  - unstructured=0.17.2
  - unstructured-client=0.34.0
  - unstructured-inference=0.8.10
  - unstructured.pytesseract=0.3.15
  - urllib3=2.4.0
  - wrapt=1.17.2
  - yarl=1.20.0
  - zstandard=0.23.0
  - pip
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiosignal==1.3.2
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - async-timeout==4.0.3
    - filetype==1.2.0
    - google-cloud-vision==3.10.1
    - googleapis-common-protos==1.70.0
    - httpcore==1.0.9
    - httpx-sse==0.4.0
    - langchainhub==0.1.21
    - pydantic-settings==2.9.1
    - pydantic_core==2.33.2
    - pyasn1==0.6.1
    - pyasn1_modules==0.4.2
    - pycocotools==2.0.8
    - pycparser==2.22
    - pypdfium2==4.30.1
    - python-iso639==2025.2.18
    - python-magic==0.4.27
    - python-multipart==0.0.20
    - python-oxmsg==0.0.2
    - types-requests==2.32.0.20250328
    - typing-inspection==0.4.0
    - unstructured.pytesseract==0.3.15
